---
- block:
  - name: Getting script from Nodesource
    ansible.builtin.get_url:
      url: "https://rpm.nodesource.com/setup_{{ nodejs_major_version }}.x"
      dest: /tmp/install_nodejs.sh
      mode: u+x
    register: downloaded

  - name: Run the script
    ansible.builtin.command: bash /tmp/install_nodejs.sh
    when: downloaded.changed

  - name: Remove the script
    ansible.builtin.file:
      path: /tmp/install_nodejs.sh
      state: absent

  - name: Install nodejs
    ansible.builtin.yum:
      name: nodejs
      state: latest

  become: true
  when: (nodejs_installed_major is undefined) or
        (nodejs_installed_major | int < nodejs_major_version | int)
